/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uiuc_bioassay_tlc_TLCApplication */

#ifndef _Included_uiuc_bioassay_tlc_TLCApplication
#define _Included_uiuc_bioassay_tlc_TLCApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uiuc_bioassay_tlc_TLCApplication
 * Method:    cleanFolder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uiuc_bioassay_tlc_TLCApplication_cleanFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_tlc_TLCApplication
 * Method:    processTLC
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_tlc_TLCApplication_processTLC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
